[project]
name = "autocycle"
version = "0.1.0"
description = "Autonomous Riderless Bike Project"
license = {text = "MIT License"}
readme = "README.md"
authors = [
    {name = "Vihaan Shah", email = "vihaan.shah@uconn.edu"},
    {name = "Kalin Kochnev", email = "kalin.kochnev@uconn.edu"},
]
maintainers = [
    {name = "Vihaan Shah", email = "vihaan.shah@uconn.edu"},
    {name = "Kalin Kochnev", email = "kalin.kochnev@uconn.edu"},
]
requires-python = ">=3.10"
dependencies = []
keywords = ["bike", "autonomous", "robotics", "underactuated"]


[project.urls]
Source = "https://github.com/uconn-hacklab/autocycle"
Tracker = "https://github.com/uconn-hacklab/autocycle/issues"
Documentation = "https://github.com/uconn-hacklab/autocycle"