services:
  autocycle: 
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USERNAME: ${USER}
    image: autocycle_dev
    container_name: autocycle_dev
    privileged: true
    user: ${USER:-${USERNAME}}
    volumes:
      - ${PWD}:${HOME}/ros_ws/
      - ./:/ros_ws
      - /tmp/.X11-unix:/tmp/.X11-unix:cached
      - /dev/dri:/dev/dri:cached
      - ~/.ssh:${HOME}/.ssh:ro
      - ~/.gitconfig:${HOME}/.gitconfig:ro
      - /dev/bus/usb:/dev/bus/usb/ 
      - /dev:/dev
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_AUTOMATIC_DISCOVERY_RANGE=LOCALHOST
      # - QT_X11_NO_MITSHM=1
      # - ROS_DOMAIN_ID=0
      # - TERM=xterm-256color
    network_mode: host
    pid: host
    ipc: host
    command: tail -f /dev/null
    working_dir: /


networks:
  default:
    name: host
    external: true
